spring:
  output.ansi.enabled: ALWAYS

property1: valuefromserver1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
